version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.4.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.4.0
    container_name: logstash
    ports:
      - 5044:5044
    command: ["-f", "/etc/logstash/conf.d", "-r"]
    volumes:
      - ./config/logstash:/etc/logstash/conf.d
      - ./config/logs:/output-logs
    depends_on:
      - elasticsearch
      
  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minIO
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio
      - MINIO_DEFAULT_BUCKETS=elk

volumes:
  test_data:
  ls_data:
  kb_data:
  minio_data: